image: node:latest
stages:
    - test
run-localchain:
    stage: test
    script:
        - yarn install --frozen-lockfile
        - yarn hardhat node
test-contract:
    stage: test
    script:
        - sleep 30
        - yarn install --frozen-lockfile
        - yarn hardhat run --network localhost scripts/deploy.js
