image: node:latest
stages:
    - run
    - test
run-localchain:
    stage: run
    script:
        - yarn install --frozen-lockfile
        - yarn hardhat node &
test-contract:
    stage: test
    script:
        - yarn install --frozen-lockfile
        - yarn hardhat --network localhost test

