stages:
    - run

run-localchain:
    stage: run
    image: golang:1.16
    script:
        - git clone https://gitlab.com/web0725/flare.git
        - cd flare
        - ./launch.sh
        - sleep 50
test-contract:
    stage: run
    image: node:latest
    script:
        - yarn install --frozen-lockfile
        - yarn hardhat --network develop test

