stages:
    - test
test-contract:
    stage: test
    image: node:latest
    before_script:
        - yarn install --frozen-lockfile
        - yarn hardhat node &
        - sleep 40
    script:
        - yarn hardhat run --network develop scripts/deploy.js
