stages:
    - test
test-contract:
    stage: test
    image: node:latest
    before_script:
        - curl -O https://dl.google.com/go/go1.16.linux-amd64.tar.gz
        - tar -C /usr/local -xzf go1.16.linux-amd64.tar.gz
        - export PATH=$PATH:/usr/local/go/bin
        - git clone https://gitlab.com/web0725/flare.git
        - cd flare
        - ./launch.sh &
        - sleep 60
    script:
        - yarn install --frozen-lockfile
        - yarn hardhat --network develop test
