image: node:latest
stages:
    - test
test-contract:
    stage: test
    image: golang:1.16
    before_script:
        - git clone https://gitlab.com/web0725/flare.git
        - cd flare
        - ./launch.sh &
        - sleep 30
    script:
        - yarn install --frozen-lockfile
        - yarn hardhat --network develop test

