stages:
    - test
test-contract:
    stage: test
    image: node:latest
    before_script:
        - yarn install --frozen-lockfile
        - yarn hardhat node &
        - sleep 150
    script:
        - yarn hardhat --network localhost test
