image: node:latest
stages:
    - run

run-localchain:
    stage: run
    script:
        - yarn install --frozen-lockfile
        - yarn hardhat node
test-contract:
    stage: run
    script:
        - yarn install --frozen-lockfile
        - yarn hardhat --network localhost test

